stack:
  name: "" # Name of the stack

githubRepoOwner: # GitHub username repo owner
githubRepoName: # GitHub repo name
githubAccessTokenName: # GitHub access token name

dev:
  account: # AWS account ID
  region: # AWS region
  deploy: false
  environmentType: dev
  branchName: dev
  pipelineConfig:
    name: # Name of the pipeline
  s3Config:
    bucketName: # Name of the bucket
    artifactsBucket: # Name of the bucket
    publicAccess: false
    indexFile: index.html
    errorFile: index.html
  domainName: # Domain name for the dev environment
  subdomainName: # Subdomain name for the dev environment
  certificateArn: # Certificate ARN for the dev environment
  

prod:
  account: # AWS account ID
  region: # AWS region
  deploy: true
  environmentType: prod
  branchName: main
  pipelineConfig:
    name: # Name of the pipeline
  s3Config:
    bucketName: # Name of the bucket
    artifactsBucket: # Name of the bucket
    publicAccess: true
    indexFile: index.html
    errorFile: index.html
  domainName: # Domain name for the prod environment
  subdomainName: # Subdomain name for the prod environment
  certificateArn: # Certificate ARN for the prod environment